- hosts: localhost
  tasks:
    - include_vars: avid_credentials.yaml

    - uri:
        url: "https://'{{ avid_server }}':3623/GateKeeper/ControlPoint/ControlPoint@'{{ avid_server }}'/Nodes/list"
        method: GET
        user: "{{ avid_username }}"
        password: "{{ avid_password }}"
        force_basic_auth: yes
        status_code: 200
     register: avid_vm_list

    - debug:
        var: avid_vm_list

