- hosts: servers
  connection: local
  tasks:
    - include_vars: vcenter_credentials.yaml

    - name: Gather only registered virtual machines
      vmware_vm_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        vm_type: vm
      delegate_to: localhost
      register: vm_facts

    - debug:
        var: vm_facts#.virtual_machines
